import type { NextPage } from "next";

import { motion } from "framer-motion";
import WorkExperience from "../components/WorkExperience";
import dynamic from "next/dynamic";
import Projects from "../components/Projects";
import About from "../components/About";
import { useState } from "react";
import Sidebar from "../components/Sidebar";
import Head from "next/head";
import { links } from "../constants/links";
import Link from "next/link";

const Skills = dynamic(() => import("../components/Skills"), { ssr: false });
const Socials = dynamic(() => import("../components/Socials"), { ssr: false });

const Home: NextPage = () => {
  const [sideBar, setSideBar] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="absolute top-0 left-0 right-0 flex justify-end pt-8 pr-8 text-teal-500">
        <ul className="justify-end hidden gap-8 sm:flex">
          {links.map((link) => {
            return (
              <Link key={link.to} href={link.to}>
                <a href="" className="transition-all hover:text-teal-100">
                  {link.name}
                </a>
              </Link>
            );
          })}
        </ul>

        <button
          className="block text-teal-500 uppercase rounded sm:hidden"
          onClick={() => setSideBar((sideBar) => !sideBar)}
        >
          <svg
            viewBox="0 0 24 24"
            width="24"
            height="24"
            stroke="currentColor"
            strokeWidth="2"
            fill="none"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <line x1="3" y1="12" x2="21" y2="12"></line>
            <line x1="3" y1="6" x2="21" y2="6"></line>
            <line x1="3" y1="18" x2="21" y2="18"></line>
          </svg>
        </button>
      </header>

      <Socials />

      <Sidebar {...{ sideBar, setSideBar }} />

      <motion.main
        className="text-slate-100 "
        animate={{
          translateX: sideBar ? -300 : 0,
        }}
        transition={{ type: "spring", bounce: 0, duration: 0.8 }}
      >
        <About />

        <WorkExperience />

        <Projects />

        <Skills />
      </motion.main>
    </>
  );
};

export default Home;
